### PR TITLE
Revert "Fix Windows"

### PR DESCRIPTION
**Pull request by TehShrike**
Reverts TehShrike/Sublime-AlphanumericMarkdownFootnote#3

It makes the tests fail.  Stupid paths...

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Weird. Where are you running the tests from? Sublime? Command line?

**Comment by TehShrike** [comment]
Command line - `python3 test.py`

**Comment by ArtskydJ** [comment]
Oh. I was running them from Sublime Text.

1. I unzipped the AlphanumericMarkdownFootnote.sublime-package file, and put the folder into `C:\Users\Joseph\AppData\Roaming\Sublime Text 3\Packages`.
2. I opened Sublime Text, and opened the console.
3. Whenever I modified a file inside `C:\Users\Joseph\AppData\Roaming\Sublime Text\Packages\AlphanumericMarkdownFootnote\`, sublime text would reload the package.
    a. With the dot, the test passed
    b. Without the dot, the test threw an error

----------

Maybe there is a way to do
```js
try {
    var FootnoteFunctions = require('footnote-functions')
} catch(e) {
    var FootnoteFunctions = require('./footnote-functions')
}
```
but in python?

**Comment by Kristinita** [comment]
@ArtskydJ , @TehShrike , is any solution, to make the plugin workable on Windows?

I installed the plugin → I restarted Sublime Text → I was getting traceback:

```python
reloading plugin Alphanumeric Markdown Footnote.AlphanumericMarkdownFootnote
reloading plugin Alphanumeric Markdown Footnote.FootnoteFunctions
reloading plugin Alphanumeric Markdown Footnote.test
Traceback (most recent call last):
  File "D:\Sublime Text Build 3211 x64 For Debug\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Sublime Text Build 3211 x64 For Debug\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\Sublime Text Build 3211 x64 For Debug\Data\Installed Packages\Alphanumeric Markdown Footnote.sublime-package\test.py", line 1, in <module>
ImportError: No module named 'FootnoteFunctions'
```

Thanks.

**Pull request merged**
